[build]
  directory = "./project"
  command = "pnpm db:push"
  functions = "netlify/functions"
  publish = "dist"

[check]
  directory = "./project"
  command = "pnpm build:workflow"
  functions = "netlify/functions"
  publish = "dist"